### ISSUE TITLE
Bug: NF_TakeFX_SetOffline isn't always restored right

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1089]
Hi !

It seems that bringing take FX offline with **NF_TakeFX_SetOffline** doesn't work nicely with all plugins : Indeed, with some of FX (like Altiverb, Speakerphone...), when the FX is restored (by the function or by the default REAPER button), the FX is restored back to default parameter, instead of being restored with the values it had before being offline.

![demo](https://i.imgur.com/o3b8qLP.gif)

Setting offline these take FX in the usual way (not with ReaScript functions) do works as expected though, so this seems to be a bug with that particular function.

Test code for one item, with one take and one FX:

```
item = reaper.GetSelectedMediaItem(0,0)
take =  reaper.GetActiveTake( item )
reaper.NF_TakeFX_SetOffline( take, 0, true )
```

Thanks for taking a look :)

**Comment by nofishonfriday** [comment]
I've [removed](https://github.com/reaper-oss/sws/pull/962/commits/a34bba40e700ff39bff5b98202a5c4dbe4959f79) these functions for next SWS version, because native [equivalents](https://www.extremraym.com/cloud/reascript-doc/#TakeFX_SetOffline) have been added meanwhile.

(Sorry, usually I try to avoid removing existing stuff, but these were only present in the last SWS pre, never officially and I think native equivalents are always preferred, so I removed them in this case.)

**Comment by X-Raym** [comment]
@nofishonfriday Ok cool !

Is there a PR which delete them ?

**Comment by nofishonfriday** [comment]
Indeed. :P

Out of curiousity, (when you've tested), does it work correctly with the native TakeFX_Get/SetOffline functions?

**Comment by X-Raym** [comment]
@nofishonfriday It seems to works indeed ! 👍

**Comment by nofishonfriday** [comment]
Thanks. Which means there was a bug in my function, good I've removed them. :D
