### ISSUE TITLE
Update C++ version

### ISSUE THREAD

**Issue by Burtan** [reaper-oss/sws#1138]
Hi,

I'm right now digging into c++ and reaper plugin developement and I'm taking sws as a resource to learn from. As far as I found out, it is still using C++98? Is there any dependency to use such an old version instead of C++14 or C++17?

Best Frederik

**Comment by Burtan** [comment]
I just tried to compile with C++14 and it worked.
Compiling with C++17 threw an error that register is no supported command anymore.

**Comment by nofishonfriday** [comment]
On OSX it also still uses C++ (GNU) 98 currently if I'm not mistaken.
So that would have to be upgraded too to stay cross platform compatible.

I'd also appreciate if we could use newer C++ features.
@swstim What do you think?

**Comment by cfillion** [comment]
I'd also love to have modern C++ in SWS. However, because we still support macOS 10.5, some modern C++ features that require linking are out of reach until we only support macOS versions that ship with a recent libc++.

I've been working toward upgrading and simplifying SWS' crossplatform build toolchain to be based on cmake, adopting modern C++ standards and implementing continuous integration.

For instance, migrating to C++17 will allow implementing the ReaScript vararg methods using only pure C++ templates without needing the php script or external dependencies (like I do in ReaPack) – #1101. 

That will require some work as SWS heavily uses deprecated/removed features such as std::auto_ptr. std::unique_ptr is not exactly the same, so each use must be reviewed.

Only MersenneTwister.h uses the deprecated `register` keyboard, so I think it can be safely `#defined` away.

Here's my work in progress branch: https://github.com/cfillion/sws/tree/cmake (I won't have time to continue work on this until June)

So far, this has been done:

- cmake project builds on all platforms, 32 and 64-bit with C++11 enabled
- Sent the JNetLib fix to upstream so that vanilla WDL can be used again
- Continuous integration for all platforms using AppVeyor and Travis CI
- Removed taglib from the repository
- Migrated to git submodules for WDL and (optionally) taglib
- Automatic generation of the macOS installer
- Tidied up build artifacts

TODO:

- Win32 installer and Linux tarball
- building BuildUtils, LangPack generation
- snprintf cleanup
- Considering generating sws_python.py at runtime (with an action)?
- Actually making SWS build with C++17
- ...

> I'm right now digging into c++ and reaper plugin developement and I'm taking sws as a resource to learn from.

This codebase is not really good. I wouldn't recommend it as a learning resource...

**Comment by nofishonfriday** [comment]
> Sent the JNetLib fix to Justin so that vanilla WDL can be used again
Should be fixed already in Justin's WDL, no?
https://github.com/justinfrankel/WDL/commit/5df98d9cec6d2d3bdd92052c63c8fbc646f63fdf

**Comment by cfillion** [comment]
Yup, it's merged (well, [part of it](https://github.com/cfillion/WDL/compare/cfillion:6a2351d907509a7d9cad43095c9f961534091e3e...jnetlib-vs2017-fix))!

**Comment by Burtan** [comment]
That sounds really good. I think I already realized that the codebase of sws is a little clustered and outdated. However, I'm getting a feel how to integrate with reaper. When cmake is ready we could think about CLion. Or do you want to remove all the project files and make it all based on cmake? I think some project files want to be in the vcs.

**Comment by Burtan** [comment]
Has anyone tried to use kotlin or rust with reaper plugins?

**Comment by Burtan** [comment]
Just a small bug, it is submodule instead of submodule**s**
`git submodule update --init`

**Comment by Burtan** [comment]
I tried your cmake branch on Linux debian with CLion but I get an error:
```
swell: dlopen() failed: /home/frederik/.config/REAPER/UserPlugins/reaper_sws64.so: undefined symbol: _Z11LICE_CircleP12LICE_IBitmapfffjfib
Error loading /home/frederik/.config/REAPER/UserPlugins/reaper_sws64.so: (null)
```

**Comment by cfillion** [comment]
Thanks! It was a link order issue. I also forgot to build sws_util_generic.cpp. Fixed along with the git submodule typo.

**Comment by Burtan** [comment]
Now I'm getting a segmentation fault.

**Comment by cfillion** [comment]
Works here, can you post the backtrace or a core dump?

**Comment by Burtan** [comment]
I got it running, it was actually my code that broke :D. Thanks for your effort!
