### ISSUE TITLE
Bug: LFO Generator can't handle take envelopes with too much points:"Could not retrieve envelope object state!"

### ISSUE THREAD

**Issue by s9menine** [reaper-oss/sws#1158]
SWS Version 2.10.0 #1 built on Feb 6 2019

Having too much envelope points on a target item causes error: "Could not retrieve envelope object state!"
Getting to a point where there would be too much envelope points is allowed. Trying to come back from it is where there's a problem.

See video: https://youtu.be/o9Q716SJKyc

Doing the same testing with Track envelopes doesn't cause an error, but causes a slow hang when creating an extreme amount of envelope points, and when using the tool while an extreme amount exists.

Also, when using LFO Generator on a stretched item, results are very inconsistent.
Using action "Xenakios/SWS: Set item rate to 1.0 and pitch to 0.0" reveals that the LFO Generator is treating the item as if it was never stretched.

**Comment by nofishonfriday** [comment]
@devs:
Issue seems here, where there's a max. size set for the envelope chunk:
https://github.com/reaper-oss/sws/blob/6963f7563851c8dd919db426bae825843939077f/Padre/padreUtils.cpp#L233

I think we could now use GetEnvelopeStateChunk() instead of GetSetEnvelopeState() (and do away with the loop) but I'm currently not sure how to use it properly:
https://forum.cockos.com/showthread.php?t=221575

**Comment by nofishonfriday** [comment]
fix merged into master in https://github.com/reaper-oss/sws/commit/2fc46c3e603ffe581a5bf8903d26f61843473650.
