### ISSUE TITLE
Q: Fader scaling toggling don't preserve values

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1176]
Hi,

I have a script which uses SWS functions to toggle Fader Scaling for selected track envelopes

Script: X-Raym_Toggle envelope fader scaling.lua

Extra basic, just a boolean to toggle.

It used to work but now the values are completly messed up:

![img](https://i.imgur.com/OYct62E.gif)

See how +3 values become something like +30... ?

It works before:

![!mg](https://i.giphy.com/3o85xHYoZBVIvhbc1W.gif)

What have change ?

Maybe on REAPER side ?

**Comment by nofishonfriday** [comment]
In current official SWS (v2.10.0 #1) there's a bug related to fader scaling, when using BR_Envelope functions.
In cfillion's build this is fixed, does is fix for you also with his version?
https://cfillion.ca/files/sws/fix-brenvelope-scaling/

**Comment by X-Raym** [comment]
@nofishonfriday ok this works !

Hmmm... Do we plan any release soon ? :p

**Comment by nofishonfriday** [comment]
Yes, a new SWS release is (over)due imo.
Would be nice to get [Justin's fixes](https://forum.cockos.com/showthread.php?p=2166896#post2166896) in and released (along with the other stuff here) when the Reaper TCP / MCP overhaul goes official otherwise I'll expect a few reports about broken scripts. :D

I just wanted to ping cfillion on slack about it, but he has a 'vacationing' sign so I respect that..
