### ISSUE TITLE
Bug in reading true peak inside loudness for video files

### ISSUE THREAD

**Issue by charlyromero** [reaper-oss/sws#1210]
As I show you in the image, reading the true peak for video files (.mp4), gives disarrayed and extreme values.

![error lectura true peak mp4](https://user-images.githubusercontent.com/56529514/66732508-a37a7d80-ee32-11e9-836b-1498bbd353e3.jpg)

I hope you review it, and thank you very much for the development of the SWS, it greatly facilitates my work within Reaper.

**Comment by cfillion** [comment]
Confirmed. We have fixed two similar bugs recently, but this one appears to be different. Are you using the VLC decoder or ffmpeg?

**Comment by charlyromero** [comment]
I am using VLC decoder. It is recommended by Reaper https://wiki.cockos.com/wiki/index.php/Video_Support

Of Course, Thank so much

**Comment by charlyromero** [comment]
I leave you to watch a video (not listed) on YouTube to see this error in detail, with some it does and others do not. 

https://youtu.be/GLKEdjdzixY

I show two examples. In the description is the download link of these files

**Comment by cfillion** [comment]
Thanks!

The root cause appears to be a bug in REAPER. I have reported it here: https://forum.cockos.com/showthread.php?t=226151.

SWS is also at fault here for producing those insane true peak measurements. Fixing that for the next version.

In the meantime you can do any of the following to avoid triggering the bug:

- Use the "Analyze selected tracks" mode instead of "Analyze selected items"
- Trim the end of the media item a little bit
- (Random chance)
