### ISSUE TITLE
What is the last compatible version for XP

### ISSUE THREAD

**Issue by TooLoose** [reaper-oss/sws#1332]
I am unable to secure a working version on my XP service pack 2 platform beyond 2.9.8  5mar2018 
Invocation of these dialogs from the Extensions item on the main menu bar results in the error reaper has encountered a problem and needs to close which it does when you accept the error dialog. 
These dialogs exhibit the problem. 
Cycle Action Editor
Find
Notes
Live Configs
Region Playlist
Resources
All on  Reaper 5.9.83
 I have tried various configurations. I come to the conclusion that changes were made to these dialogs that rendered them XP incompatible.  Does anybody have working later version of SWS beyond 2.9.8 on windows XP?  Thanks.

**Comment by cfillion** [comment]
Thanks for reporting! The crash should be fixed in these builds:

- 32-bit: https://ci.appveyor.com/api/buildjobs/xubhjymfbsmfvf9g/artifacts/build%2Fsws-2.11.0.0-Windows-x86-winxp-no-threadlocal-22633574.exe
- 64-bit: https://ci.appveyor.com/api/buildjobs/91bajm7a51ct36k2/artifacts/build%2Fsws-2.11.0.0-Windows-x64-winxp-no-threadlocal-22633574.exe

**Comment by TooLoose** [comment]
I shall test over next 24hrs. Thanks so much for quick response.

**Comment by TooLoose** [comment]
That seems to work great. XP service pack 2 Reaper 5.9.83. SWS 2.11.0.0.
Thanks so much.
