### ISSUE TITLE
Add linux download on the main website

### ISSUE THREAD

**Issue by nicola-lunghi** [reaper-oss/sws#1340]
the sws extension on linux works great please add a linux download link on the website

Thanks!
Nick

**Comment by szymsza** [comment]
Agreed. Or at least a noticeable link to the build guidline next to the Windows and OS X download links would be cool. It was not easy for me to find the tutorial because the link is hidden under the Open source section in small font size. 

![Screenshot from 2020-05-16 11-32-21](https://user-images.githubusercontent.com/12534237/82116281-ec980480-9768-11ea-925f-276dd8d04082.png)

It is really shame in my opinion that the plugin works great on Linux, yet something as simple as a visible link might prevent a lot of people from using it.

**Comment by cfillion** [comment]
Linux download links are here for now, until the next stable release: https://www.sws-extension.org/download/pre-release/.

**Comment by nicola-lunghi** [comment]
I know but is really difficult to find! There's no link to it! At least put a link to the bleeding edge page!!!! Please!! Linux now is my main platform I got 3ms latency and no issue at all!!!!

**Comment by cfillion** [comment]
v2.12.1.3 is now live on the main website!
