### ISSUE TITLE
GetTakeType() fails with video processor

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#1380]
https://github.com/reaper-oss/sws/blob/4683d071001b7a708d8364276fc324371c4f3576/Breeder/BR_Util.cpp#L828-L854

Currently it returns audio type when calling it with a video processor take.
I've added a commit (https://github.com/nofishonfriday/sws/commit/8a3ef7c14a9357507b865baae5013eb3e3798e2f) for this in my WIP [fix-xen-rename-source-reversed](https://github.com/nofishonfriday/sws/tree/fix-xen-rename-source-reversed) branch because I planned to use it there, if the branch doesn't get merged (not sure yet) the commit could be cherry-picked (or done separately).

**Comment by cfillion** [comment]
I never heard of video processor takes, how are they created?

I'm working on a patch that rewrites `GetTakeType` for #1355, I can add that before I submit it.

**Comment by nofishonfriday** [comment]
Yep.
Actually I thought it would also be nice exposing this function to ReaScript (as there isn't a way to do this natively afaik).
What do you think?

**Comment by cfillion** [comment]
Good idea. Because the type is a property of the source, I think such an API function should take a PCM_source* rather than a MediaItem_Take*. It could simply be a simple one-liner like `return source ? source->GetType() : "";` in fact.

Perhaps be we should add "SWS/BR: Select all video processor items" and support for them in contextual toolbars as well. These are the only current uses of `GetTakeType` in SWS.

(That'll make it a non-bugfix change... Not a big deal though.)

**Comment by nofishonfriday** [comment]
> Because the type is a property of the source, I think such an API function should take a PCM_source* rather than a MediaItem_Take*. 
Agreed.

> It could be a simple one-liner like return source ? source->GetType() : ""; in fact.
A bit undecided about this one. Because it would take away a bit from the simplicity of the current [https://github.com/nofishonfriday/sws/commit/8a3ef7c14a9357507b865baae5013eb3e3798e2f#diff-38f14b3be5b8da0901e68efe3b675fdbR136](internal implementation) to check if a take (source) is an audio file (which is a rather common use case I think), because `source->GetType()` returns WAV, FLAC etc. for audio files.
But on the other hand it provides more detail than just returning `audio` and scripter can check for themselves (by excluding all REAPER non-audio media types). 
So yes, returning full details is probably better. :)

**Comment by cfillion** [comment]
Done (sorry for the long hiatus, been busy...). There's already a `SNM_GetSourceType` but it gives the raw source type (so WAV/FLAC/MP3 etc) in a FastString. I'm thinking of deprecating that and introducing:

     int CF_GetMediaSourceType(PCM_source*, char *typeOut)

I've split the internal `GetTakeType` into `GetTakeRootSource` and `GetSourceType`. Do you think the former also needs to be exposed to ReaScript (it's just the "SECTION" source handling)?

**Comment by nofishonfriday** [comment]
Nice you're back. :)

I like the idea combining `GetTakeType` and `GetSourceType` into one function.
Though I'm wondering if it's actually needed as there is also a native [GetMediaSourceType](https://www.extremraym.com/cloud/reascript-doc/#GetMediaSourceType).

> Do you think the former also needs to be exposed to ReaScript (it's just the "SECTION" source handling)?

What might be interesting regarding "SECTION" is if we could access e.g. if a source is looped/reversed which is also handled there and there seems no API for it yet.
https://forum.cockos.com/showthread.php?t=242839
(In the Item state chunk it's handled in the `<SOURCE SECTION` `MODE` entry it seems but I don't know if we could access it other than chunk parsing. The other values there like LENGTH, OVERLAP might also be interesting to have access to, not sure)

**Comment by cfillion** [comment]
> Though I'm wondering if it's actually needed as there is also a native GetMediaSourceType.

The main feature over the existing functions is the integer return value that groups together every audio source types.

I now moved the SECTION handling back into `GetSourceType` so it automatically resolves the subsource's type. In C++ `GetSourceType` takes either a `PCM_source*` or a `MediaItem_Take*` so it behaves exactly like the old `GetTakeType`.

If there's little use for that though I'd rather not export the new function (but still deprecate `SNM_GetSourceType` because there's the native `GetMediaSourceType`).
