### ISSUE TITLE
Reaper warning message: S&M warning - no slot added to [path] empty directory

### ISSUE THREAD

**Issue by giannicapra** [reaper-oss/sws#1401]
Hi,
I've just installed the plugin on my Windows 10 WS, and when from Reaper I open the Extensions -> resources menu, select the FXchain and click the first icon on the left inside the resources windows I get the following message:

No slot added from [the FWChains path on my WS, which is the defalut one]. Probable cause: all files are already present, empty directory, directory not fount.

In my case il the REAPER/FXChains direcotry which is empty.
How can i solve this one?

Thank you in advance for your help.

**Comment by nofishonfriday** [comment]
Hi,

> Probable cause: all files are already present, empty directory, directory not fount.
> In my case il the REAPER/FXChains direcotry which is empty.

This sounds like you haven't actually created (saved) any FX chains from within Reaper so the Resources window can't find any it can add (as the message is saying).

Try first saving an FX chain to default location, then click the first icon again.
!(https://i.imgur.com/6PrHUBx.jpg)

As this issue seems more like a 'how to' question than a feature request or bug report (what this issue tracker is intended for) I'm closing it (for now) and suggest to post for further help in the Reaper forum.
(If you think this is actually a bug please get back and we can reopen it.)
