### ISSUE TITLE
Rename sourcefile issue

### ISSUE THREAD

**Issue by PhotonatorAudio** [reaper-oss/sws#1496]
If i type in something like "02 - Bass" it does not rename anything in the explorer. 
But reaper expect the new Filename and the track is Offline.

If i type in "02 - Bass.wav" the file in the explorer is now "02 - Bass.wav.wav".
The File keeps online

Reaper v6.19 | Win10 Pro 10.0.18363 Build 18363

**Comment by nofishonfriday** [comment]
Hi,
there is a bug in current official SWS witht that action in that it appends the file extension again if already present (as you're reporting), should be fixed in current SWS pre-release:

> v2.11.0 pre-release build (December 3, 2019)
> "Xenakios/SWS: Rename takes and source files...": (Issue 1140)
>     Don't double-append file extension if already contained in new filename/takename

So I'd first suggest updating to the latest SWS pre-release from [here](https://www.sws-extension.org/download/pre-release/), try again and report back if it works or still fails.
Thanks.

**Comment by PhotonatorAudio** [comment]
It works, thank you.

**Comment by nofishonfriday** [comment]
Thanks for reporting back.
As a sidenote: The above fix is currently only in `Xenakios/SWS: Rename takes and source files... (no undo)` but it's still missing in `Xenakios/SWS: Rename take source files... (no undo)`, but it will be in the next pre-release.
