### ISSUE TITLE
Bug report: "Play from mouse cursor position (perform until shortcut released)" breaks arrange view

### ISSUE THREAD

**Issue by maxhenderson43** [reaper-oss/sws#1551]
Noticed that calling the action "SWS/BR: Play from mouse cursor position (perform until shortcut released)" when the mouse cursor is outside the arrange viewport seems to completely break the arrange view. The grid, markers and regions get collapsed to a single point on the left-hand side and the items aren't visible. The edit cursor/selection position is shown as 0.nan / 0:00.00. 

<img width="1440" alt="Screenshot 2021-08-11 at 00 00 20" src="https://user-images.githubusercontent.com/88749991/128945679-dfbf034c-f6d8-4372-9a15-7a110bbf9b17.png">

Saving and reopening the project doesn't seem to fix this problem and I haven't found a way to restore the original state once this bug happens.

I haven't found this bug with the action "SWS/BR: Play from mouse cursor position" but it does happen with the other "perform until shortcut released" actions.

Using SWS 2.12.1.3, REAPER 6.33 and 6.34, Mac OS 11.2 and an M1 Macbook Pro 2020.

Would much appreciate any help on this issue :)

**Comment by jeremybernstein** [comment]
Can you unpack "when the mouse cursor is outside the arrange viewport"? I can't reproduce under macOS 10.15 (Intel 64-bit), but I can imagine that I'm also not understanding how to reproduce. How are you triggering the action?

**Comment by nofishonfriday** [comment]
I can reproduce on Windows.
Steps:
- open action list (Actions > Action list...)
- assign a keyboard shortcut to said action
- resize Reaper so that it doesn't cover full screen (but make sure it's still focused so it receives keyboard shortcuts)
- move mouse cursor outside of the Reaper window
- trigger the action via the assigned keyboard shortcut

![broken arrange](https://i.imgur.com/dvHCspj.jpg)

**Comment by jeremybernstein** [comment]
I've tried this on a fresh REAPER 6.3.6 install + SWS 2.12.1.3 on a Mac M1 and Mac Intel machine, and cannot reproduce. The window definitely has keyboard focus (confirmed that the same key works when playing from edit position). 

There must be some step I'm missing. Maybe because I'm using an empty project to start (with a few tracks and empty MIDI items), or something short? Stumped.

**Comment by jeremybernstein** [comment]
Nor can I reproduce on a clean install of REAPER on Windows 10 (albeit hosted in a VM -- I have a real PC in my studio, and I can try to reproduce on that system, as well).

**Comment by jeremybernstein** [comment]
Bingo, that's it. Thanks, I can take a closer look now.
