### ISSUE TITLE
Can you help me out with the compiling process?

### ISSUE THREAD

**Issue by ars4l4n** [reaper-oss/sws#1574]
Hi,
I just wanted to change the font height of the SWS note window from 14 to 22 on this file: https://github.com/reaper-oss/sws/blob/master/SnM/SnM.h and then compile it.
Unfortunately, I don't haven't done this before so I don't exactly understand how to proceed.
Trying to follow the [compiling instructions](https://github.com/reaper-oss/sws/wiki/Building-the-SWS-Extension#usage) you provided under "Usage" I ran `git clone --recursive https://github.com/reaper-oss/sws` and
`cd sws `in CMD, changed the font height inside the file, ran that reaper action, saved the generated file under C:\Users\my_name\AppData\Roaming\REAPER
I then ran `cmake -B build -DCMAKE_BUILD_TYPE=Debug` but got an error that the command "cmake" is either written incorrectly or couldn't be found.
Same thing with `cmake --build build`

What should I do now?

**Comment by cfillion** [comment]
Did you install the [Build Tools for Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) or the Visual Studio IDE? Once installed, CMake and the Microsoft's C++ compiler should be available using the "x64 Native Tools Command Prompt for VS 2019" shortcut (rather than regular cmd.exe).

The next version of SWS in the works adds a setting to S&M.ini for customizing the font size of the notes window's text field. Here's an experimental (and still incomplete) build: https://ci.appveyor.com/api/buildjobs/0ocdljvqbumnwash/artifacts/build%2Fsws-2.13.0.0-Windows-x64-v2.13-b9f69231.exe.

**Comment by ars4l4n** [comment]
Thank you for your reply
The file doesn't contain any code worded "Fontsize", so I assume I need to write a line regarding that myself? I don't know how to do it though.

**Comment by cfillion** [comment]
Yes, the line must be added manually. Can you double-check the new version is being loaded (it should show 2.13 in the about window) and the line in S&M.ini is formatted like this:

![S&M.ini](https://i.imgur.com/qimSDW5.png)

**Comment by ars4l4n** [comment]
no idea what I went wrong before but now it works, thank you
