### ISSUE TITLE
Bug: "Xenakios/SWS: Play selected items once" plays beyond end of selected item

### ISSUE THREAD

**Issue by ScottChesworth** [reaper-oss/sws#1601]
Reproduction steps:

1. Place three items containing audio right next to each other on a track. For consistency, here's the file I was making when I noticed the issue, three copies of this in a line should work: https://www.dropbox.com/s/mr5s1bd2ug7hu5k/Scott%20Error.wav?dl=1
2. Select the second item, then run "Xenakios/SWS: Play selected items once".

Expected behaviour: the item should play, starting cleanly at the left edge of the selected item and ending cleanly at the right edge.

Actual behaviour: start is clean, but I'm hearing a few MS of the next item along before transport stops. The amount of overshoot seems to vary slightly each time I run the action.

Thanks in advance if there's anything you can do to tighten this up. Shout if I can provide any more info that'd be helpful.

**Comment by nofishonfriday** [comment]
I had a look at the source code and this function uses a timer internally, so depending on where the timers triggers stop, a small portion of a consecutive item could also be heard (that's the effect you noticed with _'The amount of overshoot seems to vary slightly each time I run the action'_).

While admittedly not ideal behaviour this action wasn't intended to be sample-accurate (given the underlying code), so I'm closing this issue with a 'live with it (for now)', sorry.

@cfillion
If you think otherwise, feel free to reopen.

**Comment by ScottChesworth** [comment]
Thanks for looking into it anyway man. Appreciate it.
