### ISSUE TITLE
cycle action editor "insert selected action in action window" broken since 6.47

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1609]
The cycle action editor is kind of broken since the update to 6.47. Might have to do with the action overhaul. Any action I try to add from the action list to a cycle action is not recognized anymore. 

Here I am inserting the infamous no-op action (ID 65535) into a cycle action and it's not recognized. Is it only on my computer ? 

[url=https://ibb.co/hH6MFJy][img]https://i.ibb.co/hH6MFJy/juyhtgrfeds.png[/img][/url]

Edit : Ok so you can actually add actions in cycle actions, but you have to enter manually the command ID. Not that bad but new.

**Comment by nofishonfriday** [comment]
Seems it breaks here: https://github.com/reaper-oss/sws/blob/4ca0494874c3b38cac5372bc56505835e46150ac/SnM/SnM_Window.cpp#L501
(`lParam` no longer containing the `command ID` since the action list overhaul).

No idea how to fix (yet), I know there's 'new' native API `PromptForAction()` but it's not the same as it always starts with an all actions unselected action list).

**Comment by nofishonfriday** [comment]
update: https://forum.cockos.com/showpost.php?p=2527570&postcount=12
