### ISSUE TITLE
Bug: Emoji Encoding Issue with SWS Notes in Edition Mode

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1725]
Hi,

SWS, 2.13.2.0
Windows 10 x64,

Some composed emojis are decomposed when using SWS notes in edition mode.
🧞‍♀️ in no edit mode become 🧞♀️

Here is a demo:

![img](https://i.imgur.com/HIefkIW.gif)

Note this is just a display bug, if I go back to the no edit mode, it displays nicely.

Thx!

**Comment by cfillion** [comment]
Guessing this is related to text layout & rendering in the Windows Edit control (handling of the Zero Width Joiner control char) rather than encoding... Anyway, some findings:

1. It works in the Actions filter field and Project Settings notes
2. It works in Windows Run (`Win+R`)
3. It does not work in Windows Notepad (except in secondary fields line in Find)
4. It does not work in ReaPack's filter (Unicode windows)
5. It does not work in other SWS text edit fields (ANSI windows)

No idea what's different between those at the moment.

**Comment by X-Raym** [comment]
Maybe not useful but there was the same issue in reaper forum, thought it was for a very different reason according to justin ( https://forum.cockos.com/showpost.php?p=2638985&postcount=14 )
