### ISSUE TITLE
Loudness normalization should be the same for MONO and STEREO files

### ISSUE THREAD

**Issue by raaphorst** [reaper-oss/sws#1769]
When you run the action 'Normalize loudness of selected items to -23 LUFS' or 'Normalize loudness of selected items to -23 LUFS' this will apply -23 LUFS to STEREO and -23 LUFS to MONO files/tracks. This is wrong because this way the MONO item/track will be 3 db louder than the STEREO tracks. 

Maybe for backwards compatibility leave these actions as they are but add new actions which set MONO items/tracks to -26 LUFS and STEREO to -23 LUFS. This way MONO and STEREO items and tracks will get the same loudness.

**Comment by nofishonfriday** [comment]
When you say stereo items do you mean dual mono items (identical content on left and right channel) specifically or any stereo content?

**Comment by raaphorst** [comment]
I mean true stereo, so left and right contain different material. The -23 LUFS rule should applied to these items. Same as for -26 rule to a mono file.

**Comment by nofishonfriday** [comment]
> When you run the action 'Normalize loudness of selected items to -23 LUFS' or 'Normalize loudness of selected items to -23 
> LUFS' this will apply -23 LUFS to STEREO and -23 LUFS to MONO files/tracks. This is wrong because this way the MONO 
> item/track will be 3 db louder than the STEREO tracks.

Hm...I would say technically it's correct but the issue manifests when playing back these mono items in a 2 channel context (which is admittedly almost always the case), then they sound 3 dB too loud, would you agree?
So the feature request would be a scanning mode which calculates mono items with 3 dB less than their actual loudness value is, is this correct?

(Not to give false hopes, just trying to be clear about this FR,  I'm not planning to implement this currently.)

 Btw. Reaper obviously applies the same loudness scanning/normalizing mechanism as SWS does currently (not accounting for mono items).
23dB mono sine wave, Track 1: item normalized to -23 LUFS i with SWS, Track 2: item normalized to -23 LUFSi via Reaper's Item properties/Normalize.

![norm](https://github.com/reaper-oss/sws/assets/7658194/dfb2e58a-27e8-4a51-92e3-96225bba2bcb)

**Comment by nofishonfriday** [comment]
I forgot, since SWS v2.13 [pre-release](https://www.sws-extension.org/download/pre-release/) there's a new dual-mono scanning mode option (accessable via SWS/BR: Analyze loudness...).
With this option enabled it scans mono items 3 dB louder, meaning when normalizing to say -23LUFS it actually normalizes to -26LUFS.
I think this covers your request, so I'll close this one.
(If you think otherwise post back and we can reopen...)

**Comment by raaphorst** [comment]
thanks, that is cool. any idea when this will be in the stable version of SWS?

**Comment by nofishonfriday** [comment]
Making official SWS releases is difficult currently (due to internal/organizational stuff), last official release was v2.12.1 #3 - February 06, 2021. So currently I'd suggest using current SWS pre-releases anyway as I'd consider them more stable than last official version (in terms of bug fixes etc.).

**Comment by raaphorst** [comment]
Thanks for the clarification!

**Comment by raaphorst** [comment]
I find it confusing which version to pick from https://www.sws-extension.org/download/pre-release/

I am on OSX Big Sur. Might switch to M2 Mac soon.
