### ISSUE TITLE
Need for SWS update

### ISSUE THREAD

**Issue by billtipp** [reaper-oss/sws#1779]
I received this message when attempting to install the current version of SWS extensions on a 2022 Apple M1 Max machine:

“reaper_sws-arm64.dylib” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

I believe everything is installed correctly-it seems to be found. Is there a  newer version of the extensions than 2021? Is there something different about the installation on on M1 machine? What am I doing wrong?

**Comment by cfillion** [comment]
Yes there is a newer version here (with better compatibility with recent REAPER versions): https://www.sws-extension.org/download/pre-release/.

However that is completely unrelated to the problem you are having. Installing SWS on recent macOS versions (since Catalina) requires a few additional steps: https://github.com/reaper-oss/sws/wiki/Installing-the-SWS-Extension-(for-end-users)#macos.

**Comment by billtipp** [comment]
cfillion--Thanks for the tip on the newer version of the extension.  New version installed and everything works fine.
