### ISSUE TITLE
CF_PCM_Source_SetSectionInfo cause a click at the end of previewing

### ISSUE THREAD

**Issue by dsyrock** [reaper-oss/sws#1806]
In certain situations, when using CF_PCM_Source_SetSectionInfo with offset and length parameters, there is an audible click sound at the end of playback. The following link is an audio file I used for testing. When running the code below, a noticeable click is produced at the end, which is not present in the original file. I even need to set a fadeout of about 1 second to eliminate it.

[shoot.wav for test](https://drive.google.com/file/d/1IprlsuCUMF0lKN3Tsu2k2araOXo1FfCW)

```
path='e:\\shoot.wav'
source=reaper.PCM_Source_CreateFromFile(path)
section = reaper.PCM_Source_CreateFromType('SECTION')
reaper.CF_PCM_Source_SetSectionInfo(section, source, 0.4, 1.2, false)
pv = reaper.CF_CreatePreview(section)
reaper.PCM_Source_Destroy(source)
reaper.PCM_Source_Destroy(section)
reaper.CF_Preview_Play(pv)
```

**Comment by dsyrock** [comment]
[shoot.zip](https://github.com/reaper-oss/sws/files/13519337/shoot.zip)
Sorry, I have re-uploaded the file. Actrally, the position where I set the playback to stop is very close to zero, not from a very loud volume. With the same settings, playback is normal in Reaper. Additionally, I have found a workaround to temporarily address the click issue. By keeping the offset at 0 and using CF_Preview_SetValue to set D_POSITION instead of offset, I can achieve playback results identical to Reaper.

**Comment by cfillion** [comment]
Thanks, confirmed! Turns out it's the "Fade" parameter of the section source. `CF_PCM_Source_SetSectionInfo` sets it to 10ms. (Or rather, it doesn't set it and REAPER defaults to that.)

The same result can be obtained by inserting the file in the project and changing the section settings in the media item properties window:

![Screen Shot 2023-11-30 at 22 27 24](https://github.com/reaper-oss/sws/assets/4297676/7642a9e2-10ab-4176-9410-e82e7f45131a)

Adding an optional parameter to `CF_PCM_Source_SetSectionInfo` to control that setting, defaulting to 0. Strangly REAPER's `PCM_Source_GetSectionInfo` is lacking it...

There will be builds you can try out in about an hour at #1807.

**Comment by dsyrock** [comment]
Thanks and glad to help!
