### ISSUE TITLE
BR_Win32_GetWindowText string length limit

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1896]
The function is limited to returning only 1 kb long string, even though the length of the source string could be greater.

For example **JS_Window_GetTitle** returns much longer strings, 16 kb at least. Didn't try to figure out the limit.

Because of this it cannot be used to reliably retrieve text from SWS Notes window.

Could the limit be increased?

It can be worked around with NF_GetSWSTrackNotes or by falling back on Julian's function but relying on a single one would be cleaner and more straightforward.

**Comment by cfillion** [comment]
The buffer and its size is provided by the caller for both functions (non-ReaScript only). When called from Lua, `JS_Window_GetTitle` gets a `char[32_768]` because of the "NeedBig" flag in the parameter name. `BR_Win32_GetWindowText` gets the default `char[1024]`.

`NF_GetSWSTrackNotes` is the superior way for getting notes though. Better than relying on a specific HWND hierarchy (an implementation detail) which could change any time.

**Comment by Buy-One** [comment]
The inconvenience may lie in the fact that tracks could be many while the window is always the same, as in my use case. So you'd need to track down the specific track (no pun intended) in order to get the correct notes.

Thank you for granting the request.
