### ISSUE TITLE
Normalize items to peak RMS: Process selected items as one

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#371]
_From [mercadon...@gmail.com](https://code.google.com/u/104532005306159910903/) on September 08, 2011 02:43:44_

It would be great if we had an option in the "Set RAM analyze/normalize options" to treat all selected items as one. This way, the action "Normalize items to peak RMS" will analyze all selected items, find the highest peak RMS among them and apply it as if it were a single "glued" item, for example.

Thanks!

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=371_

**Comment by budda963** [comment]
Is there any way to get this ported over to AAX?  perhaps somebody could help me move it into JUCE?

**Comment by Breeder** [comment]
This is using native REAPER API (to extract audio and then analyze it), I'm not really sure you could port it to AAX (REAPER even doesn't support AAX). Regarding JUCE, I'm not really sure what do you mean...SWS is not like audio plugins...it's a complete extension that gets loaded exclusively by REAPER where it registers various actions that trigger multiple of things.

If you're just talking about the maths behind it, it shouldn't be too hard to understand since it's just your normal RMS and peaks...here's the main piece of analysis code behind it:
https://github.com/Jeff0S/sws/blob/master/Misc/Analysis.cpp#L74-L137
